version: "3.8"

services:
  app:
    image: "${DOCKER_HUB_USERNAME}/sopkathon-be-app:latest"
    container_name: sopkathon-be-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: "jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
      SPRING_DATASOURCE_USERNAME: "${DB_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - /home/ubuntu/sopkathon-be-app/.env:/app/.env
    env_file:
      - .env